"""Gradio demo for the Track B hallucination detector (Phase 6, Step 6.2).

A single self-contained app for Hugging Face Spaces. Per the phase doc, the demo loads
the model DIRECTLY (Detector / RAGPipeline), rather than depending on a separately-running
FastAPI process (api/main.py) -- so a Space is one process with no internal HTTP hop.

Two tabs:
  - "Paste your own": context + response -> Detector.predict() -> verdict banner +
    gr.HighlightedText spans.
  - "Live RAG": a question -> RAGPipeline (retriever + Groq + detector). Preset buttons are
    served from a checked-in cache (app/demo_cache.json) and never touch Groq; only a
    genuinely custom typed question hits the live API, with GenerationError surfaced as a
    clean message instead of a stack trace.

Spans are rendered against the REAL Detector shape ({start, end, text}; no per-span
"label" -- the token-level model doesn't emit one, the same correction api/main.py made),
so gr.HighlightedText is fed the "entities" form with one fixed category.

Expensive objects (Detector, Retriever index, Groq client) are loaded ONCE at launch via
load_models(), mirroring the API's lifespan pattern -- never at import, so tests importing
this module stay hermetic. The Groq client is built lazily and tolerated-if-absent: with no
GROQ_API_KEY the preset examples still work from cache and only custom questions are gated.

Caching decision -- app/demo_cache.json is CHECKED IN (regenerated by app/precompute_cache.py,
not at startup). The generator runs at temperature=0.6 (src/rag/pipeline.py:51), so
startup-computed answers wouldn't reproduce the vetted demo verdicts, and HF Spaces free-tier
cold starts would fire live Groq calls (and risk rate limits) exactly when a visitor arrives.
A frozen JSON keeps the demo deterministic and working even if Groq is down or no key is set.
"""

import json
import sys
from pathlib import Path

# Put the repo root on sys.path so `import src.*` resolves regardless of the launch CWD
# (HF Spaces launches from the repo root; a local `python app/app.py` does too, but this
# keeps it robust either way). Must run before the src imports below.
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

import gradio as gr  # noqa: E402

from src.models.predict import Detector  # noqa: E402
from src.rag.pipeline import GenerationError, RAGPipeline, create_groq_client  # noqa: E402
from src.rag.retriever import CORPUS_DIR, Retriever  # noqa: E402

# One fixed highlight category: our spans have no per-span label, so every flagged span is
# the same "hallucination" entity, colored red via gr.HighlightedText(color_map=...).
HALLUCINATION_LABEL = "hallucination"
COLOR_MAP = {HALLUCINATION_LABEL: "red"}

CACHE_PATH = Path(__file__).resolve().parent / "demo_cache.json"

_VERDICT_LABELS = {"🔴": "Likely hallucination", "🟡": "Borderline", "🟢": "Looks supported"}

# Loaded once by load_models() at launch (see module docstring); None until then so importing
# this module never downloads a checkpoint or needs a Groq key.
DETECTOR: Detector | None = None
PIPELINE: RAGPipeline | None = None


# --- Pure helpers (unit-tested in tests/test_app.py) ----------------------------------


def build_highlight(response: str, spans: list[dict]) -> dict:
    """Detector spans -> a gr.HighlightedText value in "entities" form.

    Each span is {start, end, text} with offsets into `response`; we drop `text` (the
    widget slices it back out of `response[start:end]`) and tag every span with the single
    HALLUCINATION_LABEL category. Empty spans -> the response shown with no highlight.
    """
    return {
        "text": response,
        "entities": [{"entity": HALLUCINATION_LABEL, "start": s["start"], "end": s["end"]} for s in spans],
    }


def format_verdict(verdict: dict) -> str:
    """Render a verdict dict as a Markdown banner (reusing the emoji from color_from_score)."""
    color = verdict["color"]
    label = _VERDICT_LABELS.get(color, "Unknown")
    return f"## {color} {label}\nScore: **{verdict['score']:.3f}**"


def format_contexts(contexts: list[dict], ablation: bool = False) -> str:
    """Render retrieved chunks (source filename + score + preview) as Markdown.

    In ablation mode a warning banner makes explicit that the generator never saw this
    context (ADR-016), so a flagged answer is a genuine parametric-knowledge hallucination.
    """
    lines: list[str] = []
    if ablation:
        lines.append(
            "> ⚠️ **Ablation mode** — the model did NOT see this context; it answered from its "
            "own parametric knowledge. The detector still checks the answer against this real "
            "retrieved context.\n"
        )
    lines.append("### Retrieved context")
    for c in contexts:
        preview = c["text"][:400].strip()
        lines.append(f"**[{c['source']}]** · similarity {c['score']:.3f}\n\n{preview}…")
    return "\n\n".join(lines)


def load_cache(path: Path = CACHE_PATH) -> dict:
    """Load the precomputed preset cache; return {} if it hasn't been generated yet."""
    path = Path(path)
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {}


def get_cached_result(question: str, cache: dict) -> dict | None:
    """Return the stored result dict for a preset question, or None if not cached."""
    return cache.get(question)


CACHE = load_cache()


# --- Model loading (once, at launch) --------------------------------------------------


def load_models() -> None:
    """Load Detector + Retriever index + Groq client once. Called from launch, not import.

    The Groq client is optional: if GROQ_API_KEY is unset, create_groq_client() raises
    RuntimeError and PIPELINE stays None -- preset examples still work from CACHE, only
    custom live questions are disabled.
    """
    global DETECTOR, PIPELINE
    DETECTOR = Detector.from_pretrained()
    retriever = Retriever()
    retriever.build(CORPUS_DIR)
    try:
        client = create_groq_client()
    except RuntimeError:
        PIPELINE = None
    else:
        PIPELINE = RAGPipeline(retriever, DETECTOR, client)


# --- Tab callbacks (thin wrappers over the helpers + loaded models) -------------------

_NO_KEY_MESSAGE = (
    "## ⚙️ Live RAG unavailable\n"
    "`GROQ_API_KEY` is not set. Add it to `.env` locally (or as a Hugging Face Spaces "
    "secret) to ask your own questions. The preset examples below still work — they are "
    "served from a checked-in cache and never call the API."
)


def analyze(context: str, response: str):
    """Tab 1 callback: run the detector directly on user-supplied context/response."""
    verdict = DETECTOR.predict(context, response)
    return format_verdict(verdict), build_highlight(response, verdict["spans"])


def _render_rag_result(result: dict):
    """Shared Tab-2 renderer: result dict -> (contexts md, verdict banner, highlighted answer)."""
    contexts_md = format_contexts(result["contexts"], ablation=result.get("ablation", False))
    verdict = result["verdict"]
    return (
        contexts_md,
        format_verdict(verdict),
        build_highlight(result["answer"], verdict["spans"]),
    )


def ask_live(question: str):
    """Tab 2 custom-question callback: the ONLY path that hits the live Groq API."""
    if PIPELINE is None:
        return _NO_KEY_MESSAGE, "", None
    try:
        result = PIPELINE.answer(question)
    except GenerationError as exc:
        # exc message is already user-facing and key-free (pipeline.py contract).
        return f"### ⚠️ Generation failed\n{exc}", "", None
    return _render_rag_result(result)


def show_preset(question: str):
    """Tab 2 preset-button callback: render a cached result, never calling Groq."""
    result = get_cached_result(question, CACHE)
    if result is None:
        return (
            "### ⚠️ Not cached\nNo precomputed result for this preset. Run "
            "`python app/precompute_cache.py` to generate `demo_cache.json`.",
            "",
            None,
        )
    return _render_rag_result(result)


# --- UI -------------------------------------------------------------------------------

# Tab 1 preset (context, response) pairs. Verdicts (comments) are REAL, from running
# Detector.predict() during planning -- kept here so the examples stay honest if edited.
TAB1_EXAMPLES = [
    # 🟢 0.094, 0 spans -- clean, fully supported.
    [
        "Carl Friedrich Gauss (1777-1855) was a German mathematician. He made major "
        "contributions to number theory, including his 1801 work Disquisitiones "
        "Arithmeticae, and proved the fundamental theorem of algebra.",
        "Gauss contributed to number theory and published Disquisitiones Arithmeticae in 1801.",
    ],
    # 🔴 0.988 -- precise partial catch: only the invented Fields Medal clause is flagged.
    [
        "Carl Friedrich Gauss (1777-1855) was a German mathematician who made major "
        "contributions to number theory and published Disquisitiones Arithmeticae in 1801.",
        "Gauss published Disquisitiones Arithmeticae in 1801 and won the Fields Medal in 1820.",
    ],
    # 🔴 0.994 -- blatant: the whole invented sentence is flagged.
    [
        "Marie Curie was a physicist and chemist who conducted pioneering research on "
        "radioactivity. She was born in Warsaw in 1867 and won two Nobel Prizes.",
        "Marie Curie was born in Paris in 1901 and personally invented the telephone.",
    ],
    # 🔴 0.967 -- KNOWN FALSE POSITIVE (docs/notes.md): this answer is factually CORRECT;
    # the detector is over-sensitive to paraphrase. Shipped as an honest limitation example.
    [
        "Bernhard Riemann was born in 1826 in Breselenz. He was the second of six children "
        "of his father Friedrich Bernhard Riemann, a pastor.",
        "Riemann was the second of six children, meaning he had five siblings.",
    ],
]

# Tab 2 preset questions (mirror pipeline.main()); results come from CACHE, not live Groq.
TAB2_PRESETS = [
    ("Grounded · in corpus", "What did Gauss contribute to number theory?"),
    ("Grounded · out-of-corpus refusal", "Who won the 2022 FIFA World Cup?"),
    (
        "Ablation · no context (live-hallucination demo)",
        "On what exact date did John von Neumann marry his second wife, Klara Dan?",
    ),
]


def build_demo() -> gr.Blocks:
    """Construct the Gradio UI. Kept in a function so importing this module builds nothing.

    Tab-2 preset buttons are declared AFTER the output components so their .click can target
    them (Gradio requires the output components to exist when wiring an event).
    """
    with gr.Blocks(title="RAG Hallucination Detector") as demo:
        gr.Markdown(
            "# 🔎 RAG Hallucination Detector\n"
            "A ModernBERT token-level detector (Track B) that highlights the exact spans of a "
            "response **not supported** by its context."
        )

        with gr.Tab("Paste your own"):
            gr.Markdown(
                "Paste a **context** and a **response**. The detector scores the response and "
                "highlights any spans the context does not support."
            )
            with gr.Row():
                t1_context = gr.Textbox(label="Context", lines=8, placeholder="Source text…")
                t1_response = gr.Textbox(label="Response", lines=8, placeholder="Answer to check…")
            t1_button = gr.Button("Analyze", variant="primary")
            t1_verdict = gr.Markdown()
            t1_highlight = gr.HighlightedText(label="Response (flagged spans in red)", color_map=COLOR_MAP)

            t1_button.click(analyze, inputs=[t1_context, t1_response], outputs=[t1_verdict, t1_highlight])
            gr.Examples(examples=TAB1_EXAMPLES, inputs=[t1_context, t1_response], label="Examples")
            gr.Markdown(
                "_The Riemann example is a **known false positive** — that answer is actually "
                "correct; the detector is over-sensitive to paraphrase (see docs/notes.md)._"
            )

        with gr.Tab("Live RAG"):
            gr.Markdown(
                "Ask a question about the five-mathematician corpus (Gauss, Euler, Hilbert, "
                "Riemann, von Neumann). The pipeline retrieves context, generates an answer with "
                "Groq, and the detector checks it.\n\n"
                "**Preset buttons are cached** (no API call). Only a custom typed question calls Groq."
            )
            t2_question = gr.Textbox(label="Question", placeholder="Ask about the corpus…")
            t2_button = gr.Button("Ask (live)", variant="primary")
            t2_contexts = gr.Markdown()
            t2_verdict = gr.Markdown()
            t2_highlight = gr.HighlightedText(label="Answer (flagged spans in red)", color_map=COLOR_MAP)
            t2_outputs = [t2_contexts, t2_verdict, t2_highlight]

            t2_button.click(ask_live, inputs=t2_question, outputs=t2_outputs)

            gr.Markdown("**Cached demo questions** (instant, no API call):")
            with gr.Row():
                for label, question in TAB2_PRESETS:
                    gr.Button(label, size="sm").click(show_preset, inputs=gr.State(question), outputs=t2_outputs)

    return demo


if __name__ == "__main__":
    load_models()
    build_demo().launch()
